# .github/workflows/build.yml
# 2025
# By Pedro Henrique Garcia.
# Github/gitlab: Phkaiser13

name: Compilação e Verificação de CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Tornar Gradle Wrapper executável
        run: chmod +x ./IntelliJ-To-Gradle/gradlew

      - name: Compilar com Gradle (subdiretório IntelliJ-To-Gradle)
        working-directory: ./IntelliJ-To-Gradle
        run: ./gradlew build
